# -*- coding: utf-8 -*-
"""分類01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a3Zk1B8FqvELeHBf34lhuELi8HMky6wd
"""

#使用所蒐集的資料,分析, 建立模型, 作為資料分析使用, AI
#ML (Machine Learning)
#資料相關性-> 迴歸 (SLR 簡單線性迴歸) -> 多元迴歸 (MLR) : 資料的相關性以及預測
# 房價資料預測, 市政府共享單車需求數量預測, 身高體重 -> 想課程的專題
# 資料分類 (classification)

#紅酒: 法國, 義大利, 南非, 美國, 澳洲
#義大利：Barolo, Grignolino, Babera
#酒精、頻果酸、灰分、鹼度、鎂、苯酚、非黃酮化合物、花青素、色澤、色調、吸光度、普胺酸, 黃酮類

# KNN (K-nearest neighbors) 最近鄰居演算法
from sklearn import datasets
from sklearn.model_selection import train_test_split
#取得資料
data, target = datasets.load_wine(return_X_y=True)
target
#3分鐘練習, 7:06
type(target)

data_train, data_test, target_train, target_test = train_test_split(data, target, test_size=0.2, random_state=0)

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)
#3分鐘練習, 7:15
knn.fit(data_train, target_train)

pre = knn.predict(data_test)
print(pre)
print(target_test)
print(knn.score(data_train, target_train).round(2))
print(knn.score(data_test, target_test).round(2))
#Overfitting
#5分鐘練習, 7:25

from sklearn.metrics import classification_report
print(classification_report(target_test, pre))
#precision 精準率 (當預測資料為第N類猜對的比例)
#recall 召回率 (在所有第 N 類資料中, 正確被預測為第 N 類的筆率) -> 3 分鐘練習, 7:35

#第一節課休息, 至7:47