# -*- coding: utf-8 -*-
"""分類02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ROYerFdp24-Ma5YyosLmOnW87o5-CodM
"""

#羅吉斯 (Logistic)
#病人是否有糖尿病, 心臟病, 狀態是否致命; 機器設備一年後是否故障; 颱風是否造成土石流; 某個人是否投給某個政黨
#迴歸 0-1, 機率
#羅吉斯迴歸函數

from sklearn import datasets
from sklearn.model_selection import train_test_split
data, target = datasets.load_wine(return_X_y=True)

from sklearn.preprocessing import StandardScaler #標準化處理 -> 3 分鐘, 8:32
sc = StandardScaler()
data_std = sc.fit_transform(data)
data_train, data_test, target_train, target_test = train_test_split(data_std, target, test_size=0.2, random_state=0)
#3分鐘完成到這裡, 7:59

from sklearn.linear_model import LogisticRegression
log_model = LogisticRegression(max_iter=10000)
log_model.fit(data_train, target_train)
pre = log_model.predict(data_test)
print(pre)
print(target_test)
#3分鐘完成至此, 8:05

#迭代次數, 套件的預測順練次數100次 -> 3 分鐘練習, 8:20

print(log_model.score(data_train, target_train).round(2))
print(log_model.score(data_test, target_test).round(2))

from sklearn.metrics import classification_report
print(classification_report(target_test, pre))
#3分鐘產出報表, 8:12

#資料標準化 (standardization, normalization)
#舉例：
#資料一：10 , 20, 30, 40, 50
#資料二：500, 1000, 1500, 200, 2500

#第二節休息, 8:45 繼續
#原本二月5日有排課, 那天不上課, 往後延一次。