# -*- coding: utf-8 -*-
"""外部檔案資料匯入與系統目錄控制.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ArIQJLBksTKNfNy1cTLTdM6Ff2HzbzvY
"""

# https://data.gov.tw/dataset/40448
# csv (comma seperated values)

import pandas as pd
df = pd.read_csv(r'aqx.csv', usecols=['sitename', 'aqi', 'co', 'o3', 'pm10', 'pm2.5', 'no2', 'no'], index_col='sitename')
print(df) #8:18

df = df.apply(pd.to_numeric, errors='coerce')

df.describe()

import matplotlib.pyplot as plt
import seaborn as sns
sns.heatmap(df.corr(), annot=True)
plt.show()

import os
print(os.getcwd())

print(os.getcwd())
os.rmdir('first_test')

print(os.listdir())

fds = os.listdir()
for fd in fds:
  if os.path.isdir(fd):
    print('This is directory: ', fd)
  else:
    print('Is a file: ', fd)

test_file = open('poem.txt', 'rt', encoding='utf-8')