# -*- coding: utf-8 -*-
"""1115 課程.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18gdFyVYgAQRYz3lUkTV6MgoE-4lfv7t9
"""

str1 = "如果是 中文 Python is a programming language that lets your work quickly."
list1 = str1.split()
print(list1)
str2 = "+".join(list1)
print(str2)

baseUrl = "http://example.com"
list1 = ["http://www.example.com/test", "http://example.com/word", "media/ex.jpg",
         "http://www.example.com/index.html"]

def getUrl(baseUrl, source):
  if source.startswith("http://www."):
    url = "http://" + source[11:]
  elif source.startswith("http://"):
    url = source
  else:
    url = baseUrl + "/" + source

  if baseUrl not in url:
    return None
  return url

for item in list1:
  print(getUrl(baseUrl, item))

# @title
# Data1, Data2, Data3
# 10, 33, 45
# 5, 25, 56

import csv
csvfile = "myfile.csv"
list1 = [[10, 33, 45, 88], [5, 25, 56, 99]]
with open(csvfile, 'w', newline='') as fp:
  writer = csv.writer(fp)
  writer.writerow(["Data1", "Data2", "Data3"])
  for row in list1:
    writer.writerow(row)

with open(csvfile, 'r') as fp:
  reader = csv.reader(fp)
  for row in reader:
    print(';'.join(row))

#JSON, DICT, Dictionary
import json
data = {
    "name" : "Peter Pan",
    "score" : 95,
    "lesson" : "Python"
}

json_str = json.dumps(data)
print(json_str)
data2 = json.loads(json_str)
print(data2)

jsonfile = "Example.json"
with open(jsonfile, 'w') as fp:
  json.dump(data, fp)

import requests
import time

url = 'http://worldtimeapi.org/api/ip'

while True:
  data = requests.get(url).json()
  print(data['datetime'])
  time.sleep(5)