# -*- coding: utf-8 -*-
"""DB.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BA0k2aSUDNfzIYh5UlZOFOaVqpXq1UIu
"""

# Database
# Relational Database -> RDBMS
# table, column, row

# student (Table)
# stuid   name    pid       phone
# 104001  Claire  B34222    243556
# 104002  John    J224122   22455
# 3...

#score (Table)
# stuid   sem   sub   score
# 104001  1121  CH    95
# 104001  1121  EN    83
# 104002  1121  CH    88
#...

#SQL (Structural Query Language)
# DDL (Data Definition Language): CREATE Database, CREATE Table
# DML (Data Manipulation Language): SELECT, UPDATE, DELETE
# DCL (Data Control Language): COMMIT, ROLLBACK

# CREATE
# CREATE DATABASE school

# CREATE TABLE stu (
#     stuid INTEGER(50)  not null,
#     name  VARCHAR(50)   not null,
#     pid   VARCHAR(20)   not null,
#     phone VARCHAR(10)
# )

# DROP TABLE stu
# ALTER TABLE stu ADD addr VARHCAR(100)

# SELECT, INSERT, UPDATE, DELTE

#SQLite (Oracle, IBM DB2, MS SQL Server)
import sqlite3
con = sqlite3.connect('school.db') #SQLite database

cur = con.cursor()

cur.execute("CREATE TABLE movie(title, year, score)")

cur.execute("""
INSERT INTO movie VALUES
('I love C#', 2020, 70)""")

#Insert multiple records in LIST
data = [("Batman", 1982, 98),
 ("Spiderman", 2002, 90),
  ("Antman", 2020, 89)]

cur.executemany("INSERT INTO movie VALUES(?, ?, ?)", data)
con.commit()

res = cur.execute("SELECT * FROM movie")
print(res.fetchall())
res2 = cur.execute("SELECT COUNT(*) FROM movie")
print(res2.fetchone())

#DML
res3 = cur.execute("SELECT title FROM movie WHERE year = 2022")
res3.fetchall()

res4 = cur.execute("SELECT year FROM movie WHERE title = 'Antman'")
res4.fetchall() #rest to 8:25