# -*- coding: utf-8 -*-
"""0103.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-yxXEzQVz5jo7ShKp1A8PViY2KQ4EOsj
"""

# 檔案 (excel, csv), 資料庫
# list, -> json {}

import csv
csvfile = 'exa.csv'
#開啟與與讀取 csv 資料內容
with open(csvfile, 'r') as fp:
  reader = csv.reader(fp)
  for row in reader:
    print(row)

#5分鐘練習, 至 7:05

csvfile2 = 'exa2.csv'
list1 = [[10, 20, 30], [33, 44, 55]]
with open(csvfile2, 'w', newline='') as fp:
  writer = csv.writer(fp)
  writer.writerow(['First','Second','Third'])
  for row in list1:
    writer.writerow(row)

#5分鐘練習, 至 7:20

import requests
from bs4 import BeautifulSoup
import csv

url = 'https://fchart.github.io/ML/table.html'
csv_file3 = 'company.csv'

r = requests.get(url)
r.encoding = 'utf8'
#print(r.status_code)
#print(r.text)
soup = BeautifulSoup(r.text, 'lxml')
#print(soup)
tag_table = soup.find(class_ = 'tt')
rows = tag_table.findAll('tr')
#5分鐘練習, 至7:53

with open(csv_file3, 'w+', newline='', encoding='utf-8') as fp:
  writer = csv.writer(fp)
  for row in rows:
    rowList = []
    for cell in row.findAll(['td', 'tr']):
      rowList.append(cell.get_text().replace('\n', '').replace('\r', ''))
    writer.writerow(rowList)
#請練習7分鐘, 至 8:17

# JSON -> JavaScript

import json
data = {
    "name" : "Joe Chen",
    "score" : 95,
    "tel" : "0933123456"
}

print(data)
json_str = json.dumps(data)
print(json_str)
data2 = json.loads(json_str)
print(data2)
#file.json

jsonfile = 'example.json'
with open(jsonfile, 'w') as fp:
  json.dump(data, fp)
  #3分鐘練習, 至8:31

with open(jsonfile, 'r') as fp:
  data = json.load(fp)
json_str = json.dumps(data)
print(json_str)

#練習與第二節休息到 8:45

import json
import requests

url = 'https://www.googleapis.com/books/v1/volumes?maxResults=5&q=Python&projection=lite'
jsonfile = 'Books.json'
r = requests.get(url)
r.encoding = 'utf8'
json_data = json.loads(r.text)
with open(jsonfile, 'w') as fp:
  json.dump(json_data, fp)
  #5 分鐘練習,至9:00

with open(jsonfile, 'r') as fp:
  data = json.load(fp)
json_str = json.dumps(data)
print(json_str)

import requests
url = 'https://fchart.github.io/img/fchart03.png'
path = 'fchart03.png'
response = requests.get(url, stream=True)
if response.status_code == 200:
  with open(path, 'wb') as fp:
    for chunk in response:
      fp.write(chunk)
  print("圖片已經下載.")
else:
  print("檔案 HTTP 請求失敗!")

#3分鐘練習

# data -> file : csv, json
# 資料庫
# 關聯式資料庫 (Relational Database): 家樂福, Costco, 快速儲存查詢
# SQL Server, Oracle, DB2, MySQL, SQLite

import sqlite3
conn = sqlite3.connect('Books.sqlite')