# -*- coding: utf-8 -*-
"""0111.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o00RoKsh6PJbtagD42_NfNyJRd0YwXqQ
"""

# Pandas: Series, DataFrame (Table)
# 樞紐分析表: 欄位, 列, 中間區:值
# Pivot

data = {'分類': ['居家', '居家', '娛樂', '娛樂', '科技', '科技'],
        '商店':['家樂福', '頂好', '家樂福', '全聯', '頂好', '家樂福'],
        '價格':[11.42, 23.5, 19.99, 15.95, 55.75, 111.55],
        '測試分數': [4, 3, 5, 7, 5, 8]}

data #3分鐘輸入資料,至6:52

import pandas as pd
products = pd.DataFrame(data)
products
#2分鐘

pp = products.pivot_table(index='分類',
                          columns='商店',
                          values='測試分數')

pp
#5分鐘練習, 7:08

#視覺化呈現大量資料
# matplotlib
import matplotlib.pyplot as plt
data1 = [-1, -4.3, 15, 21, 31]
#折線圖：資料變動的趨勢, 價格, 股票, 溫度
plt.plot(data1, "o--b")
plt.show()
#3分鐘畫折線圖, 7:18
#樣式搜尋關鍵字 matplotlib plot line style parameter

days = range(0, 22, 3) #x 軸
c = [17, 18, 19, 19.5, 20, 21, 22, 23]
plt.plot(days, c)
plt.show()
#3分鐘練習, 第一節課休息 7:40

import numpy as np
x = np.linspace(0, 10, 50)
sinus = np.sin(x)
cosinus = np.cos(x)
plt.plot(x, sinus, 'r-o', label='sin(x)')
plt.plot(x, cosinus, 'g--', label='cos(x)')
plt.grid(True)
plt.xlabel('The value of sin()')
plt.ylabel('cos()')
plt.title('My science plot example.')
plt.legend(loc='upper right')
plt.savefig('test.png') #儲存圖片
plt.show()
#3分鐘練習至8:07

#色彩: b, g, r, w, k
#線條:-, --, .

#散點圖, 散佈圖, scatter
x = np.linspace(0, 2*np.pi, 50)
y = np.sin(x)
plt.scatter(x, y)
plt.show()
#3分鐘練習, 8:14

x = np.random.rand(1000)
y = np.random.rand(1000)
size = np.random.rand(1000) * 50
color = np.random.rand(1000)
plt.scatter(x, y, size, color)
plt.colorbar()
plt.show()
#3分鐘練習, 8:22

#3. 長條圖 bar -> 不同群, 不同種類資料的大小
labels = ['Python', 'C++', 'Java', 'JS', 'C', 'C#']
index = np.arange(len(labels)*2)
ratings = [5.16, 5.726, 14.988, 3.165, 11.854, 4.453]
change = [1.12, 0.3, -1.69, 0.29, 3.41, -0.45]
plt.bar(index[0::2], ratings, label='Use rate')
plt.bar(index[1::2], change, label='Groth rate', color='r')
plt.legend()
plt.xticks(index[0::2], labels)
plt.ylabel('Use %')
plt.title('Most Popular Program Language')
plt.show()
#5分鐘練習, 8:56

#4.直方圖 histograms, 顯示數值資料分布, 次數分配
#常態分配 (normal distribution)
x = np.random.randn(1000)
num_bins = 50
plt.hist(x, num_bins)
plt.show()
#3分鐘練習, 9:03

#5.餅圖, 派圖 (pie chart) 顯示資料分布的 %
labels = ['Python', 'C++', 'Java', 'JS', 'C', 'C#']
ratings = [5, 6, 15, 3, 12, 4]
explode = [0, 0, 0.3, 0, 0, 0.2]
plt.pie(ratings, labels=labels, explode = explode)
plt.title('Program Language Rating')
plt.show()
#3分鐘練習, 9:12
#boxplot, radiation..

dists = {'Area': ['中正區', '板橋區', '桃園區', '北屯區', '安南區', '三民區', '大安區', '永和區', '八德區', '前鎮區', '鳳山區', '信義區', '新店區'],
         'People': [159598, 551452, 441287, 275207, 192327, 343203, 309835, 222531, 198473, 189623, 359125, 225561, 302070],
         'Place': [7, 23, 34, 62, 107, 19, 11, 5, 33, 19, 26, 11, 120]
}

df = pd.DataFrame(dists, columns=['People', 'Place'], index=dists['Area'])
print(df)
df['Place'] *= 1000
df.plot(xticks=range(len(df.index)), use_index=True, rot=90)
plt.show()
#5分鐘練習, 9:38