# -*- coding: utf-8 -*-
"""複迴歸_房價預測.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jYaAHg81V9CQn0rnLc960c4n_tFCTUO8
"""

#http://lib.stat.cmu.edu/datasets/boston
import numpy as np
import pandas as pd
raw_df = pd.read_csv('boston.csv', sep='\s+', skiprows=22, header=None)
raw_df
#3分鐘, 9:32
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]
print(data.shape)

#3分鐘練習, 9:40