# -*- coding: utf-8 -*-
"""深度學習_01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EcD5xBgf9QyQio71BI5NS_AczKxqkDji
"""

#擷取資料 -> 資料分析 -> AI = ML (機器學習) + DL (Deep Learning)
# DL 深度學習
# 神經元 (neuro) -> 樹突 -> 類神經網路 (NN, Neural Network)
# CNN -> Convolution Neural Network -> 影像

# 資料來源 https://archive.ics.uci.edu/dataset/34/diabetes
import pandas as pd
df = pd.read_csv('diabetes.csv')
print(df.head())
#3分鐘練習, 7:06

print(df.shape)

import numpy as np
from keras.models import Sequential
from keras.layers import Dense
np.random.seed(10)
dataset = df.values
np.random.shuffle(dataset)
Y = dataset[:, 8]
X = dataset[:, 0:8]
#5分鐘練習, 7:23

model = Sequential()
model.add(Dense(10, input_shape=(8,), activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.summary()
#練習5分鐘, 7:45
#第一節休息到 7:57

model.compile(loss='binary_crossentropy', optimizer='sgd', metrics=['accuracy'])

history = model.fit(X, Y, epochs=150, batch_size=10)
#7分鐘練習, 8:14

print("Model Evaluatation:")
loss, accuracy = model.evaluate(X, Y)
print("準確率 = {:.2F}".format(accuracy))
#3分鐘練習, 8:22